### ISSUE TITLE
Unwanted buttons in the tool-bar added by atom-debug-ui

### ISSUE THREAD

**Issue by vadimhp** [cchamplin/atom-debug-ui#10]
How to remove?

![untitled-1](https://user-images.githubusercontent.com/9541638/43300187-c0c7798e-912b-11e8-94b2-e2500fbbac5c.png)

Thank you!

**Comment by cchamplin** [comment]
I'm not sure which toolbar you're referring to but I don't think atom-debug-ui is adding those icons.
